name: gilbert_labvispro_week3_2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
